# Java的Throwable_Class(异常体系）
### Error是JVM内部错误
### Exception是用户编写的程序错误
---

![Optional Text](https://raw.githubusercontent.com/IDGAQ/Super_Cool_Notes/main/throwable_class.jpg)

## Error: 
1. StackOverflowError(递归，递归层次太多或递归没有结束)
2. OutOfMemoryError(堆创建了很多对象)
Exception是我们编写的程序错误

---
## Exceptions:

### 1. RuntimeException：(LogicException)
为什么编译器不会要求你去try catch处理？
本质是逻辑错误，比如空指针异常，这种问题是编程逻辑不严谨造成的
应该通过完善我们的代码编程逻辑，来解决问题
非RuntimeException：

---

### 2. 非RuntimeException(自定义）
1. 自定义try catch，throws
本质是客观因素造成的问题，比如FileNotFoundException
写了一个程序，自动阅卷，需要读取答案的路径（用户录入），用户可能录入是一个错误的路径，所以我们要提前预案，写好发生异常之后的处理方式，这也是java程序健壮性的一种体现
